#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

#
# make is calling the ./scripts/build_images.sh who calls docker-compose build
#
version: '3.7'
services:
  rover_local:
    image: rover
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - versionTerraform
        - versionAzureCli
        - versionKubectl
        - versionGit
        - versionTflint
        - versionJq
        - versionDockerCompose
        - versionTfsec
        - versionTerraformDocs
        - versionAnsible
        - versionPacker
        - versionMssqlTools
        - versionMsodbcsql17
        - versionRover

  rover_registry:
      extends: rover_local
      image: ${versionRover}

